Exception thrown: {
   "_exception" : "Foo"
}
